spring:
  datasource:
    url: jdbc:h2:file:./data/realtime-chat;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

logging:
  level:
    org.hibernate.SQL: warn
